version: "3.6"
services:
  bd:
    image: mongo
    environment:
      - AUTH=no
  back:
    image: brunogamacatao/app-mongo-backend
    depends_on:
      - bd
    environment:
      - DATABASE_URL=mongodb://bd/mongo01
      - SERVER_PORT=5000
      - SALT_ROUNDS=7
      - SECRET=M3uB@ckEnd!
      - VALIDADE_TOKEN=300
    ports:
      - "5000:5000"
  front:
    image: brunogamacatao/app-mongo-frontend
    depends_on:
      - back
    ports:
      - "3000:80"
